### ISSUE TITLE
There are vulnerabilities in project dependent components

### ISSUE THREAD

**Issue by Penglq** [dubbogo/gost#103]
**What happened**:
A total of two defective components with vulnerabilities were introduced into the project. The following are some of the main information：

infomation: [https://www.oscs1024.com/cd/1530636116259217408?sign=c65eceeb](https://sctrack.sendcloud.net/track/click/eyJuZXRlYXNlIjogImZhbHNlIiwgIm1haWxsaXN0X2lkIjogMCwgInRhc2tfaWQiOiAiIiwgImVtYWlsX2lkIjogIjE2NTc3NjA2NzA3OTdfMTYwNzcwXzQ2NTMxXzQ5MDIuc2MtMTBfOV8xM18yMTMtaW5ib3VuZDAkMTM3NDg1NDM1OUBxcS5jb20iLCAic2lnbiI6ICI4ZjFjYmI4NjFkYjg1ZjI5ZmM0MDdjNWZkMzBmZmIwZSIsICJ1c2VyX2hlYWRlcnMiOiB7fSwgImxhYmVsIjogIjIyMzEzOTExIiwgInRyYWNrX2RvbWFpbiI6ICJzY3RyYWNrLnNlbmRjbG91ZC5uZXQiLCAicmVhbF90eXBlIjogIiIsICJsaW5rIjogImh0dHBzJTNBLy93d3cub3NjczEwMjQuY29tL2NkLzE1MzA2MzYxMTYyNTkyMTc0MDglM0ZzaWduJTNEYzY1ZWNlZWIiLCAib3V0X2lwIjogIjExNy41MC4zNS4yNTIiLCAiY29udGVudF90eXBlIjogMywgInVzZXJfaWQiOiAxNjA3NzAsICJvdmVyc2VhcyI6ICJmYWxzZSIsICJjYXRlZ29yeV9pZCI6IDI1NzM0N30=.html)
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by AlexStocks** [comment]
Pls fix it. thx.
