### ISSUE TITLE
Imp: refactoring  memory pool 

### ISSUE THREAD

**Issue by AlexStocks** [dubbogo/gost#13]

**Comment by wongoo** [comment]
@AlexStocks  what's the problem for the  current implementation?  what should be improved, performance, or features, or just refactoring to let it be simple?

**Comment by AlexStocks** [comment]
@wongoo because those codes are just copied. we need to rewrite it.

**Comment by AlexStocks** [comment]
we can reserve the func name and its params as usual. however, its implementation should be rewritten.

**Comment by wongoo** [comment]
including  GetBytes/PutBytes and GetBytesBuffer/PutBytesBuffer ?

**Comment by AlexStocks** [comment]
all funcs of https://github.com/dubbogo/gost/blob/master/bytes/slice_pool.go need to be rewritten.

**Comment by wongoo** [comment]
see https://github.com/dubbogo/gost/releases/tag/v1.5.0
