### ISSUE TITLE
log里面的CInfo不能输出传入字符串

### ISSUE THREAD

**Issue by iotdog** [dubbogo/gost#39]
CPrintfln方法中fmt.Fprint应为fmt.Fprintf

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by AlexStocks** [comment]
submit ur pr, pls.

**Comment by AlexStocks** [comment]
@iotdog submit ur pr, pls.
