### ISSUE TITLE
zk ignores the error of node exists

### ISSUE THREAD

**Issue by Mulavar** [dubbogo/gost#75]
**What happened**:
in database/kv/zk/client.go, gost ignores the error of node exists,  and when I try to create some node (like dubbo/config) I didn't know it exists with CreateWithValue, I got no error and I thought it worked, but in fact, it failed.
![image](https://user-images.githubusercontent.com/23017406/139710154-35c8f27e-a7ef-479c-9cbf-32ecb97e09f0.png)

**What you expected to happen**:
When I try to create some node that exists, I want to know it, and then I can use SetContent to modify it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by wenxuwan** [comment]
I will check it,if change it , dubbo-go need check the error.
