### ISSUE TITLE
decimal package NewDecFromFloatForTest method can allowble dev env?

### ISSUE THREAD

**Issue by baerwang** [dubbogo/gost#88]
[[func NewDecFromFloatForTest(f float64) *Decimal {]()](https://github.com/dubbogo/gost/blob/9adb81a5ce494252652bf08394954ae7f21ae6ea/math/big/decimal.go#L2279)

**Comment by luky116** [comment]
i'll fix it

**Comment by luky116** [comment]
PR:https://github.com/dubbogo/gost/pull/89/files

**Comment by baerwang** [comment]
https://github.com/dubbogo/gost/pull/92
